#if defined colors_included
    #endinput
#endif
#define colors_included

#if !defined c_server
    #define c_server "{7D63FF}"
#endif

#if !defined c_white
    #define c_white  "{FFFFFF}"
#endif

#if !defined c_blue
    #define c_blue   "{3249A4}"
#endif

#if !defined c_red
    #define c_red    "{F75757}"
#endif

#if !defined c_green
    #define c_green  "{61EE99}"
#endif

#if !defined c_lblue
    #define c_lblue  "{88F4F7}"
#endif

#if !defined c_orange
    #define c_orange "{FCB764}"
#endif

#if !defined c_amber
    #define c_amber  "{BF431D}"
#endif

#if !defined c_ruby
    #define c_ruby   "{A82F31}"
#endif

#if !defined c_greey
    #define c_greey  "{7D7C7C}"
#endif

#if !defined c_lgreen
    #define c_lgreen "{17FF70}"
#endif

#if !defined c_yellow
    #define c_yellow "{FFE747}"
#endif

#if !defined c_black
    #define c_black  "{000000}"
#endif

#if !defined c_purple
    #define c_purple "{7D63AA}"
#endif

#if !defined y_server
    #define y_server 0x7D63FFFF
#endif

#if !defined y_white
    #define y_white  0xFFFFFFFF
#endif

#if !defined y_blue
    #define y_blue   0x3249A4AA
#endif

#if !defined y_red
    #define y_red    0xF75757FF
#endif

#if !defined y_green
    #define y_green  0x61EE99FF
#endif

#if !defined y_lblue
    #define y_lblue  0x88F4F7FF
#endif

#if !defined y_orange
    #define y_orange 0xFCB764FF
#endif

#if !defined y_amber
    #define y_amber  0xBF431DAA
#endif

#if !defined y_ruby
    #define y_ruby   0xA82F31FF
#endif

#if !defined y_greey
    #define y_greey  0x7D7C7CFF
#endif

#if !defined y_lgreen
    #define y_lgreen 0x17FF70FF
#endif

#if !defined y_yellow
    #define y_yellow 0xFFE747FF
#endif

#if !defined y_black
    #define y_black  0x000000FF
#endif

#if !defined y_purple
    #define y_purple 0x7D63FFAA
#endif

